jobs:
  android-compile:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        cache: npm
        cache-dependency-path: '**/package-lock.json'
        node-version: 16.x
    - continue-on-error: true
      name: Install node modules
      run: npm install
    - continue-on-error: true
      name: Install example node modules
      run: npm install
      working-directory: ./examples/GumTestApp/
    - continue-on-error: true
      name: Compile Android Example
      run: ./gradlew assembleDebug
      working-directory: ./examples/GumTestApp/android
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android_ci.yml
