jobs:
  run-ci:
    name: Lint
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - continue-on-error: true
      run: npm install
    - continue-on-error: true
      name: Check if the git repository is clean
      run: $(exit $(git status --porcelain --untracked-files=no | head -255 | wc -l))
        || (echo "Dirty git tree"; git diff; exit 1)
    - continue-on-error: true
      run: npm run lint
name: Simple CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
