jobs:
  ios-compile:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        cache: npm
        cache-dependency-path: '**/package-lock.json'
        node-version: 16.x
    - continue-on-error: true
      name: Cache cocoapods
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        path: ./examples/GumTestApp/ios/Pods
        restore-keys: '${{ runner.os }}-pods-

          '
    - continue-on-error: true
      name: Install node modules
      run: npm install
    - continue-on-error: true
      name: Install example node modules
      run: npm install
      working-directory: ./examples/GumTestApp/
    - continue-on-error: true
      name: Pod install
      run: pod install
      working-directory: ./examples/GumTestApp/ios
    - continue-on-error: true
      name: Compile iOS Example
      run: "set -o pipefail && \\\nxcodebuild -workspace GumTestApp.xcworkspace/ \\\
        \n  -scheme GumTestApp \\\n  -destination generic/platform=iOS \\\n  CODE_SIGN_IDENTITY=\"\
        \" \\\n  CODE_SIGNING_REQUIRED=NO \\\n  CODE_SIGN_ENTITLEMENTS=\"\" \\\n \
        \ CODE_SIGNING_ALLOWED=\"NO\" clean build \\\n| xcpretty\n"
      working-directory: ./examples/GumTestApp/ios
name: iOS CI
on:
  repository_dispatch:
    types: trigger-ga___ios_ci.yml
